services:
  - type: web
    name: slot-gpt-analyzer
    env: python
    buildCommand: ""
    startCommand: gunicorn main:app
    envVars:
      - key: LINE_CHANNEL_ACCESS_TOKEN
        value: your_line_channel_access_token
      - key: LINE_CHANNEL_SECRET
        value: your_line_channel_secret
      - key: DROPBOX_ACCESS_TOKEN
        value: your_dropbox_access_token
      - key: OPENAI_API_KEY
        value: your_openai_api_key
