services:
  - type: web
    name: dropbox-gpt-linebot
    runtime: python
    env: python
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: LINE_CHANNEL_SECRET
        value: YOUR_LINE_CHANNEL_SECRET
      - key: LINE_CHANNEL_ACCESS_TOKEN
        value: YOUR_LINE_ACCESS_TOKEN
      - key: LINE_USER_ID
        value: YOUR_LINE_USER_ID
      - key: OPENAI_API_KEY
        value: YOUR_OPENAI_API_KEY
      - key: DROPBOX_APP_KEY
        value: YOUR_DROPBOX_APP_KEY
      - key: DROPBOX_APP_SECRET
        value: YOUR_DROPBOX_APP_SECRET
      - key: DROPBOX_REFRESH_TOKEN
        value: YOUR_DROPBOX_REFRESH_TOKEN