services:
  - type: web
    name: slot-data-analyzer
    env: python
    plan: free
    region: singapore  # 東京が無いため、近いシンガポールを選択
    buildCommand: ""
    startCommand: "gunicorn app:app"
    autoDeploy: true
    envVars:
      - key: LINE_CHANNEL_SECRET
        sync: false
      - key: LINE_CHANNEL_ACCESS_TOKEN
        sync: false
      - key: LINE_USER_ID
        sync: false
      - key: DROPBOX_REFRESH_TOKEN
        sync: false
      - key: DROPBOX_APP_KEY
        sync: false
      - key: DROPBOX_APP_SECRET
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: MAX_TOKENS
        value: "2048"