services:
  - type: web
    name: slot-data-analyzer
    env: python
    buildCommand: ""
    startCommand: gunicorn main:app
    plan: free
    autoDeploy: true
    envVars:
      - key: LINE_CHANNEL_SECRET
        value: ${LINE_CHANNEL_SECRET}
      - key: LINE_CHANNEL_ACCESS_TOKEN
        value: ${LINE_CHANNEL_ACCESS_TOKEN}
      - key: LINE_USER_ID
        value: ${LINE_USER_ID}
      - key: OPENAI_API_KEY
        value: ${OPENAI_API_KEY}
      - key: DROPBOX_APP_KEY
        value: ${DROPBOX_APP_KEY}
      - key: DROPBOX_APP_SECRET
        value: ${DROPBOX_APP_SECRET}
      - key: DROPBOX_REFRESH_TOKEN
        value: ${DROPBOX_REFRESH_TOKEN}