services:
  - type: web
    name: slot-data-analyzer-bot
    runtime: python
    region: oregon  # または singapore / tokyo に変更可能
    plan: free
    buildCommand: ""
    startCommand: gunicorn main:app --bind 0.0.0.0:$PORT
    envVars:
      - key: LINE_CHANNEL_ACCESS_TOKEN
        value: your_line_access_token
      - key: LINE_CHANNEL_SECRET
        value: your_line_channel_secret
      - key: LINE_USER_ID
        value: your_line_user_id
      - key: DROPBOX_APP_KEY
        value: your_dropbox_app_key
      - key: DROPBOX_APP_SECRET
        value: your_dropbox_app_secret
      - key: DROPBOX_REFRESH_TOKEN
        value: your_dropbox_refresh_token
      - key: OPENAI_API_KEY
        value: your_openai_api_key
    autoDeploy: true