services:
  - type: web
    name: dropbox-line-bot
    env: python
    region: singapore
    plan: free
    buildCommand: ""
    startCommand: gunicorn main:app
    envVars:
      - key: LINE_CHANNEL_SECRET
        sync: false
      - key: LINE_CHANNEL_ACCESS_TOKEN
        sync: false
      - key: DROPBOX_APP_KEY
        sync: false
      - key: DROPBOX_APP_SECRET
        sync: false
      - key: DROPBOX_REFRESH_TOKEN
        sync: false
      - key: LINE_USER_ID
        sync: false