services:
  - type: web
    name: yatagarasu_et_labo
    env: python
    runtime: python3.11  # ←★これを追加（必須！）
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn main:app"
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: LINE_CHANNEL_SECRET
        sync: false
      - key: LINE_CHANNEL_ACCESS_TOKEN
        sync: false
      - key: DROPBOX_REFRESH_TOKEN
        sync: false
      - key: DROPBOX_CLIENT_ID
        sync: false
      - key: DROPBOX_CLIENT_SECRET
        sync: false
      - key: GITHUB_PAT
        sync: false